---
- name: Deploy Splitwise app
  hosts: all
  tasks: 
    - name: Copy docker compose file to host
      copy:
        src: ./docker-compose.yml
        dest: /home/deployments/
    - name: Remove already existing image
      docker_image: 
        name: patro30/backend
        state: absent
        force: yes
    - name: Pull updated image
      docker_image:
        name: patro30/backend
    - name: Run docker compose
      shell: docker-compose -f home/deployments/docker-compose.yml up -d