---
- name: Deploy Splitwise app
  hosts: all
  tasks:
    - name: Copy docker compose file to host
      copy:
        src: docker-compose.yml
        dest: docker-compose.yml

    - name: Stop already running docker compose
      shell: docker-compose down

    - name: Stop Running Containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

    - name: Remove Stopped Docker Containers
      shell: |
        docker rm $(docker ps -a -q);
      when: docker_info.containers != 0
      
    - name: Get all Docker Images
      docker_host_info:
        images: yes
        verbose_output: yes
      register: image_info

    - name: Remove all Docker Images
      docker_image:
        name: "{{ item }}"
        state: absent
      loop: "{{ image_info.images | map(attribute='Id') | list }}"

    - name: Pull updated image
      docker_image:
        name: patro30/backend

    - name: Run docker compose
      shell: docker-compose up -d
